server:
  port: 8081

spring:
  application:
    name: m-crm
  web:
    resources:
      static-locations: classpath:/static/
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

gg:
  jte:
    developmentMode: true
    contentType: Html
    templateLocation: src/main/resources/jte

logging:
  level:
    org.springframework.web: DEBUG
    ru.mentee.power.crm: DEBUG
    gg.jte: DEBUG